format = """
[](#89b4fa)\
[ ](fg:#11111b bg:#89b4fa)\
[](fg:#89b4fa bg:#cdd6f4)\
$directory\
[](fg:#cdd6f4 bg:#fab387)\
$git_branch\
$git_status\
[](fg:#fab387 bg:#cba6f7)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$rust\
[](fg:#cba6f7 bg:#a6e3a1)\
$docker_context\
[](fg:#a6e3a1 bg:#89b4fa)\
$time\
[ ](fg:#89b4fa)\
"""

# Disable the blank line at the start of the prompt
# add_newline = true

[directory]
style = "fg:#11111b bg:#cdd6f4"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Projects" = " "

[c]
symbol = " "
style = "fg:#11111b bg:#cba6f7"
format = '[[ $symbol ($version) ](fg:#11111b bg:#cba6f7)]($style)'

[docker_context]
symbol = " "
style = "fg:#11111b bg:#a6e3a1"
format = '[[ $symbol $context ](fg:#11111b bg:#a6e3a1)]($style) $path'

[elixir]
symbol = " "
style = "fg:#11111b bg:#cba6f7"
format = '[[ $symbol ($version) ](fg:#11111b bg:#cba6f7)]($style)'

[elm]
symbol = " "
style = "fg:#11111b bg:#cba6f7"
format = '[[ $symbol ($version) ](fg:#11111b bg:#cba6f7)]($style)'

[git_branch]
symbol = ""
style = "fg:#11111b bg:#fab387"
format = '[[ $symbol $branch ](fg:#11111b bg:#fab387)]($style)'

[git_status]
style = "fg:#11111b bg:#fab387"
format = '[[($all_status$ahead_behind )](fg:#11111b bg:#fab387)]($style)'

[golang]
symbol = " "
style = "fg:#11111b bg:##cba6f7"
#format = '[[ $symbol ($version) ](fg:#11111b bg:#cba6f7)]($style)'
format = '[[ $symbol](fg:#11111b bg:#cba6f7)]($style)'
[haskell]
symbol = " "
style = "fg:#11111b bg:#cba6f7"
format = '[[ $symbol ($version) ](fg:#11111b bg:#cba6f7)]($style)'

[java]
symbol = " "
style = "fg:#11111b bg:#cba6f7"
format = '[[ $symbol ($version) ](fg:#11111b bg:#cba6f7)]($style)'

[julia]
symbol = " "
style = "fg:#11111b bg:#cba6f7"
format = '[[ $symbol ($version) ](fg:#11111b bg:#cba6f7)]($style)'

[nodejs]
symbol = ""
style = "fg:#11111b bg:#cba6f7"
format = '[[ $symbol ($version) ](fg:#11111b bg:#cba6f7)]($style)'

[rust]
symbol = ""
style = "fg:#11111b bg:#cba6f7"
format = '[[ $symbol ($version) ](fg:#11111b bg:#cba6f7)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "fg:#11111b bg:#89b4fa"
format = '[[  $time ](fg:#11111b bg:#89b4fa)]($style)'
